### ISSUE TITLE
Drag & drop of multiple tags divided by unselected tags resulting in freeze

### ISSUE THREAD

**Issue by galantra** [glutanimate/bettertags-public#1]
## Which add-on is affected?

BetterTag – current version from Patreon

## Prerequisite checklist

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

drag multiple tags divided by unselected tags

## How can we reproduce the problem?

1. Open browser 
2. select several tags by Ctrl+leftclick
3. make sure there re unselected tags between the selected tags
4. drag the selected tags onto an unselected tag

**Expected behavior:** Selected tags will be subtags of the tag onto which you dragged them

**Actual behavior:** browser does not display notes and can only be closed by task manager, not alt+f4
Once, the rest of anki (I had the reviewer open) also freezed. The other times, I could access the main screen as well as review cards.

**Reproducible?:** yes

## Version information

**Anki**

Version 2.1.15 (6661ba8a)
Qt 5.12.1 PyQt 5.11.3

**System**

- Operating system: Windows
- Version: 10

**Comment by glutanimate** [comment]
Just created a dedicated repo to host the bug tracking for BetterTags. Moving the issue there.

**Comment by glutanimate** [comment]
This should be fixed with [BetterTags v1.0.0](https://www.patreon.com/posts/bettertags-v1-0-33338657). Thanks again for taking the time to report this, and sorry it took so long to address!
